// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mijnZorgRooster.Data;

namespace mijnZorgRooster.Migrations
{
    [DbContext(typeof(ZorginstellingContext))]
    [Migration("20181220132229_zorgapp")]
    partial class zorgapp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("mijnZorgRooster.Models.Certificate", b =>
                {
                    b.Property<int>("CertificaatID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum");

                    b.Property<int>("MedewerkerID");

                    b.Property<DateTime>("geldigTot");

                    b.HasKey("CertificaatID");

                    b.HasIndex("MedewerkerID");

                    b.ToTable("Certificate");
                });

            modelBuilder.Entity("mijnZorgRooster.Models.Contract", b =>
                {
                    b.Property<int>("ContractID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BeginDatum");

                    b.Property<int>("ContractUren");

                    b.Property<DateTime>("Einddatum");

                    b.Property<int>("ParttimePercentage");

                    b.Property<int?>("medewerkerID");

                    b.Property<int>("verlofDagenPerJaar");

                    b.HasKey("ContractID");

                    b.HasIndex("medewerkerID");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("mijnZorgRooster.Models.Medewerker", b =>
                {
                    b.Property<int>("medewerkerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Achternaam");

                    b.Property<string>("Adres");

                    b.Property<string>("Emailadres");

                    b.Property<DateTime>("Geboortedatum");

                    b.Property<string>("MobielNummer");

                    b.Property<string>("Postcode");

                    b.Property<string>("Telefoonnummer");

                    b.Property<string>("Tussenvoegsels");

                    b.Property<string>("Voornaam");

                    b.Property<string>("Woonplaats");

                    b.HasKey("medewerkerID");

                    b.ToTable("Medewerker");
                });

            modelBuilder.Entity("mijnZorgRooster.Models.Roll", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("medewerkerID");

                    b.HasKey("RolID");

                    b.HasIndex("medewerkerID");

                    b.ToTable("Roll");
                });

            modelBuilder.Entity("mijnZorgRooster.Models.Certificate", b =>
                {
                    b.HasOne("mijnZorgRooster.Models.Medewerker", "Medewerker")
                        .WithMany("Certificates")
                        .HasForeignKey("MedewerkerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("mijnZorgRooster.Models.Contract", b =>
                {
                    b.HasOne("mijnZorgRooster.Models.Medewerker", "Medewerker")
                        .WithMany("Contracts")
                        .HasForeignKey("medewerkerID");
                });

            modelBuilder.Entity("mijnZorgRooster.Models.Roll", b =>
                {
                    b.HasOne("mijnZorgRooster.Models.Medewerker")
                        .WithMany("Rolls")
                        .HasForeignKey("medewerkerID");
                });
#pragma warning restore 612, 618
        }
    }
}
